server:
  port: 8080
  host: "0.0.0.0"

queue:
  worker_count: 5
  buffer_size: 100
  retry_limit: 3
  retry_delay: 60

storage:
  type: "redis"
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0

logger:
  level: "info"
  format: "json"